In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
import pickle as pkl

In [2]:
df=pd.read_csv("com_data.csv")

In [3]:
df

District       Time  Temperature in deg  Temperature in fer  \
0     Adilabad   4/1/2016                  38               100.4   
1     Adilabad   4/2/2016                  40               104.0   
2     Adilabad   4/3/2016                  41               105.8   
3     Adilabad   4/4/2016                  41               105.8   
4     Adilabad   4/5/2016                  37                98.6   
...        ...        ...                 ...                 ...   
9130  Warangal  9/26/2020                  25                77.0   
9131  Warangal  9/27/2020                  26                78.8   
9132  Warangal  9/28/2020                  27                80.6   
9133  Warangal  9/29/2020                  28                82.4   
9134  Warangal  9/30/2020                  27                80.6   

      Dew Point in Deg  Dew Point in fer  Humidity  Wind Speed      Pressure  \
0                   -2              28.4        11    8 | 4.97  29.77 | 1008   
1                    3              37.4        14    6 | 3.73  29.77 | 1008   
2                    9              48.2        21    8 | 4.97   29.8 | 1009   
3                    9              48.2        21    7 | 4.35  29.74 | 1007   
4                   11              51.8        26    8 | 4.97  29.77 | 1008   
...                ...               ...       ...         ...           ...   
9130                23              73.4        91   12 | 7.46  29.68 | 1005   
9131                22              71.6        84  18 | 11.18  29.74 | 1007   
9132                22              71.6        81    8 | 4.97  29.71 | 1006   
9133                23              73.4        81   10 | 6.21  29.71 | 1006   
9134                23              73.4        84   10 | 6.21  29.68 | 1005   

     Precipitation         R  Relative Humidity  Heat Index  
0        0.0 | 0.0 -0.146916           7.946419   94.806511  
1        0.0 | 0.0  0.215785          10.257329   98.663572  
2        0.0 | 0.0  0.631573          14.741169  102.464666  
3        0.0 | 0.0  0.631573          14.741169  102.464666  
4       3.7 | 0.15  0.765699          20.897719   96.010559  
...            ...       ...                ...         ...  
9130   45.9 | 1.81  1.527143          88.680636   78.243877  
9131    7.2 | 0.28  1.466384          78.641721   81.705717  
9132   15.5 | 0.61  1.466384          74.141290   84.575368  
9133    3.4 | 0.13  1.527143          74.310124   88.263408  
9134   23.6 | 0.93  1.527143          78.785768   85.328433  

[9135 rows x 13 columns]

In [4]:
df['Time']=pd.to_datetime(df['Time'])

In [5]:
df['month'] = pd.DatetimeIndex(df['Time']).month

In [6]:
data=df.loc[:,['District','Temperature in deg','Dew Point in Deg','Heat Index','month']]

In [7]:
data

District  Temperature in deg  Dew Point in Deg  Heat Index  month
0     Adilabad                  38                -2   94.806511      4
1     Adilabad                  40                 3   98.663572      4
2     Adilabad                  41                 9  102.464666      4
3     Adilabad                  41                 9  102.464666      4
4     Adilabad                  37                11   96.010559      4
...        ...                 ...               ...         ...    ...
9130  Warangal                  25                23   78.243877      9
9131  Warangal                  26                22   81.705717      9
9132  Warangal                  27                22   84.575368      9
9133  Warangal                  28                23   88.263408      9
9134  Warangal                  27                23   85.328433      9

[9135 rows x 5 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()

In [9]:
data['District']=LE.fit_transform(data['District'])

In [10]:
data

District  Temperature in deg  Dew Point in Deg  Heat Index  month
0            0                  38                -2   94.806511      4
1            0                  40                 3   98.663572      4
2            0                  41                 9  102.464666      4
3            0                  41                 9  102.464666      4
4            0                  37                11   96.010559      4
...        ...                 ...               ...         ...    ...
9130         3                  25                23   78.243877      9
9131         3                  26                22   81.705717      9
9132         3                  27                22   84.575368      9
9133         3                  28                23   88.263408      9
9134         3                  27                23   85.328433      9

[9135 rows x 5 columns]

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [12]:
X=data.drop(['Heat Index'],axis=1)

In [13]:
Y=data.loc[:,['Heat Index']]

In [14]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=42,test_size=0.20)

In [16]:
RFR=RandomForestRegressor()

In [17]:
RFR.fit(x_train,y_train)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_364\1229064473.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFR.fit(x_train,y_train)


RandomForestRegressor()

In [18]:
y_pred=RFR.predict(x_test)

In [19]:
y_pred

array([ 78.4105968 ,  96.28055528,  91.94044657, ...,  91.33928046,
       102.0457922 ,  81.74712988])

In [20]:
y_test.values

array([[ 78.4105968 ],
       [ 96.32055453],
       [ 91.94044657],
       ...,
       [ 91.41021771],
       [102.0457922 ],
       [ 81.74712988]])

In [24]:
print("R2 Score:-",r2_score(y_test,y_pred)*100)

R2 Score:- 99.98421172503133


In [26]:
print("mean_absolute_error:-",mean_absolute_error(y_test,y_pred))

mean_absolute_error:- 0.014042312087872436


In [27]:
print("mean_squared_error:-",mean_squared_error(y_test,y_pred))

mean_squared_error:- 0.011536662377537968


In [31]:
RFR.predict([[0,43,15,4]])

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([110.08968902])

In [32]:
RFR.predict([[0,36,15,4]])

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([96.51889783])

In [33]:
RFR.predict([[0,32,15,4]])

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([88.82085483])

In [53]:
RFR.predict([[0,70,20,4]])

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([110.62281429])

In [29]:
pkl.dump(RFR,open('model.pkl', 'wb'))